# Generated by Django 3.0.8 on 2020-07-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('institution', models.CharField(blank=True, max_length=1024, null=True)),
                ('city_or_place', models.CharField(blank=True, max_length=1024, null=True)),
                ('institution_type', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(blank=True, max_length=1024, null=True)),
                ('country', models.CharField(blank=True, max_length=1024, null=True)),
                ('further_details', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'verbose_name_plural': 'Institutions',
                'db_table': 'anabin_all_countries',
                'ordering': ['pk'],
                'managed': False,
            },
        ),
    ]
